### ISSUE TITLE
More Powerful Attributes (e.g. as function middleware)

### ISSUE THREAD

**Issue by tobyselway** [pxp-lang/pxp#5]
My suggestion is to improve upon PHP's current Attributes system (https://www.php.net/manual/en/language.attributes.overview.php) by allowing them access to manipulate the way a function is interacted with. This would allow an attribute to "wrap" or "be wrapped by" a function it is applied to.

This would allow things like this to be possible:
(Original idea by @enunomaduro on Twitter)

```php
#[Dd]
public function foo() {
    return "bar";
}
```
This attribute would automatically dd the return value of the function it is applied to.

A possible implementation of this could be as follows:

```php
#[Attribute]
class Dd {
    public function __after($retval) {
        dd($retval);
    }
}
```

Here I present the __after method that is triggered after a function has been called and is provided with the return value of the function.
This idea could be expanded to include a __before method that could allow mutating the input parameters to a function, or even conditionally avoid calling the function entirely. This could be useful for validation purposes.

e.g.

```php
#[GreaterThan(4)]
public function foo(int $a) {
    // Here I am certain that $a is > 4
    return $a + 2;
}
```

```php
#[Attribute]
class GreaterThan {

    protected $val;

    public function __construct($val) {
        $this->val = $val;
    }

    public function __before($params) {
        if($params[0] <= $this->val) {
            throw new ValidationException("...");
        }
        return $params;
    }
}
```

I'm quite sure there are better ways of accessing parameters in the __before function, as well as many other aspects of this that can be improved upon. All feedback is welcome.

Original thread about this concept on Twitter:
https://twitter.com/ryangjchandler/status/1614611643253530624

**Comment by HenrivantSant** [comment]
This would be great!! However functionality wise it seems quite similar to this (https://wiki.php.net/rfc/property_accessors) RFC already under discussion for native PHP.

So it might be wise to maybe wait that out before there’s two language APIs to accomplish the same functionality which might actually confuse people.

If the RFC doesn’t pass I would love to see this implemented. I see quite a few useful implementations for this in the userland. Especially for generated code in frameworks and ORMs.
