### ISSUE TITLE
[BUG] Some errors have detailed explanations: E0026, E0308, E0412, E0432, E0433, E0532, E0769.

### ISSUE THREAD

**Issue by denisgolius** [pxp-lang/pxp#6]
Hi!
I've tried to build pxp from https://pxplang.org/getting-started/installation.html#setup but I failed to issue. See log below:

```
Some errors have detailed explanations: E0026, E0308, E0412, E0432, E0433, E0532, E0769.
For more information about an error, try `rustc --explain E0026`.
error: could not compile `pxp` due to 65 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `pxp v0.0.0-b1 (https://github.com/pxp-lang/pxp#9f0adde0)`, intermediate artifacts can be found at `/tmp/cargo-installULorXc`  
```
Here is my config
```
❯ cargo -V
cargo 1.66.1 (ad779e08b 2023-01-10)

~ 
❯ uname -a
Linux asus 5.18.19-051819-generic #202208211443 SMP PREEMPT_DYNAMIC Sun Aug 21 15:10:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

~
❯ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian

openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
```

What I'm doing wrong?

**Comment by ryangjchandler** [comment]
Hi, the main command-line tool isn't ready for any form of usage yet and is undergoing some restructuring. I've temporarily removed the installation instructions from the website to avoid any confusion.

A new version for you to try out will be available soon.

**Comment by denisgolius** [comment]
> Hi, the main command-line tool isn't ready for any form of usage yet and is undergoing some restructuring. I've temporarily removed the installation instructions from the website to avoid any confusion.
> 
> A new version for you to try out will be available soon.

Ok, thanks for letting know.
Btw: ubuntu 20.04 show other error but the problem still exist.
