### ISSUE TITLE
Limit diagnostics to one per span / position

### ISSUE THREAD

**Issue by ryangjchandler** [pxp-lang/pxp#77]
The diagnostics that get generated in the parser stack up right now, so if you write some bad code, we end up dumping a bunch of diagnostics on you.

This is less than ideal and I personally think there should only be one diagnostic at a time. Once you've fixed one, you'll see the next one and can progressively fix the problem.

At the same time, we should probably make sure our diagnostics actually make sense too.

**Comment by zeina1i** [comment]
Hey @ryangjchandler 
Can I take this issue?

**Comment by ryangjchandler** [comment]
@zeina1i Absolutely, feel free to tackle this one and open a PR!
